name: portfolio
description: A personal portfolio built on Flutter for web
author: Arne Molland <arneolaim@gmail.com>

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  english_words: ^3.1.5
  vector_math: ^2.0.8
  recase: ^2.0.1

dev_dependencies:
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
