import 'dart:convert';
import 'dart:io';
import 'package:recase/recase.dart';

void main(List<String> arguments) {
  var file = new File(arguments.first);

  if (!file.existsSync()) {
    print('Cannot find the file "${arguments.first}".');
  }

  var content = file.readAsStringSync();
  Map<String, dynamic> icons = json.decode(content);

  Map<String, String> iconDefinitions = {};

  for (String iconName in icons.keys) {
    var icon = icons[iconName];
    var unicode = icon['unicode'];
    
    iconDefinitions[iconName] = generateIconDefinition(
      iconName,
      unicode,
    );
  }

  List<String> generatedOutput = [
    "import 'package:flutter_web/widgets.dart';",
    "import 'package:portfolio/icons/feather_icon_data.dart';",
    '',
    '// THIS FILE IS AUTOMATICALLY GENERATED!',
    '',
    'class FeatherIcons {',
  ];

  generatedOutput.addAll(iconDefinitions.values);

  generatedOutput.add('}');

  File output = new File('feather.dart');
  output.writeAsStringSync(generatedOutput.join('\n'));
}

String generateIconDefinition(String iconName, String unicode) {
  String iconDataSource = 'IconData';

  iconName = new ReCase(iconName).camelCase;

  return 'static const IconData $iconName = const FeatherIconData(0x$unicode);';
}